### ISSUE TITLE
Corrupted frames 

### ISSUE THREAD

**Issue by swapnilsayansaha** [OpenThermal/libseek-thermal#44] opened 2020-06-16 01:03 UTC
I have connected the seek thermal camera to a Raspberry Pi like board running on Ubuntu. I followed all the instructions. However, I am getting corrupted frames like this:

![image](https://user-images.githubusercontent.com/20337475/84720159-2e67c680-af32-11ea-897f-290abf898bd2.png)

![image](https://user-images.githubusercontent.com/20337475/84720211-4e978580-af32-11ea-86e0-b0733f2a3570.png)

Board connection:

![image](https://user-images.githubusercontent.com/20337475/84720233-5eaf6500-af32-11ea-9b56-4df2b7c95937.png)

Anyone knows what's going wrong? I dont see any error in the terminal.

**Comment by zeeblezooble** [comment] 2020-07-15 10:20
Hello, I had a similar issue, and posted solution [here](https://github.com/maartenvds/libseek-thermal/issues/36#issuecomment-658680474).

**Comment by alxpettit** [comment] 2020-09-13 00:11
What board is that? It looks like a jetson nano.

**Comment by Bostwickenator** [comment] 2021-01-02 18:25
Duplicate of #36

**Closed by Bostwickenator** 2021-01-02 18:25 UTC
